#FROM cypress/base:12
FROM cypress/browsers:node14.17.0-chrome91-ff89
RUN mkdir /my-cypress-project
WORKDIR /my-cypress-project
COPY ./package.json .
COPY ./package-lock.json .
COPY ./cypress.json .
COPY ./cypress ./cypress
COPY ./.env .
#RUN apt-get install libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
RUN npx ci
#RUN npx install
#RUN npx run start:ci &
ENTRYPOINT ["npx", "cypress","run"]
CMD [""]
EXPOSE 8080
